//! `XcallTarget` — the xcall experiment's target contract, importable from
//! its compiled artifact alone.
//!
//! GENERATED by `minocrab-interface-gen` from the callee's own compactc
//! artifact. Edit the artifact or the generator, never this file: `cargo
//! test -p minocrab-interface-gen` regenerates it and fails on any
//! difference.
//!
//! Source artifact:
//! `corpus/zkir/signet-midnight-experiments/experiments/xcall/contract/src/target`
//! (compiler 0.33.0, language 0.25.0, runtime 0.18.0-rc.1), pinned by
//! `artifact/pin.json` and checked by `tests/artifact_agreement.rs`.
//!
//! DECLARATION ORDER IS THE WIRE CONTRACT. A circuit's parameters and a
//! struct's fields flatten, in order, into the limbs hashed into the
//! communications commitment the ledger matches — so reordering or retyping
//! either changes the commitment and breaks every deployed caller.
//! `artifact/interface-schema.txt` freezes that layout; its diff is the
//! semver decision (notes/interface-crates.org §"Versioning and
//! publishing").
//!
//! EVERY ARGUMENT AND RESULT IS `Public`, because passing a value to
//! another contract discloses it: it enters the commitment in the clear. A
//! private value must `c.disclose(…)` first, and forgetting is a compile
//! error.
//!
//! THE INTERFACE CONTAINS NO ADDRESS. `XcallTarget::at_field(index)` names
//! the sealed ledger cell a deployment keeps the address in, and
//! `XcallTarget::at(address)` takes one as data.

use minocrab::Public;
use minocrab_std::v3::{interface, BytesN, Uint, B32};

/// ```text
/// contract XcallTarget {
///   circuit deposit(recipient: Bytes<32>, amount: Uint<128>): [];
///   circuit depositEmit(recipient: Bytes<32>, amount: Uint<128>): [];
///   circuit depositBig(data: Bytes<256>): [];
/// }
/// ```
#[interface]
pub trait XcallTarget {
    /// `circuit deposit(recipient: Bytes<32>, amount: Uint<128>): []`
    fn deposit(recipient: B32<Public>, amount: Uint<128, Public>);

    /// `circuit depositEmit(recipient: Bytes<32>, amount: Uint<128>): []`
    fn deposit_emit(recipient: B32<Public>, amount: Uint<128, Public>);

    /// `circuit depositBig(data: Bytes<256>): []`
    fn deposit_big(data: BytesN<Public, 256>);
}
