//! `SignetSigner` — the cross-contract interface of the Sig Network Signet
//! singleton, as an importable crate.
//!
//! GENERATED by `minocrab-interface-gen` from the callee's own compactc
//! artifact. Edit the artifact or the generator, never this file: `cargo
//! test -p minocrab-interface-gen` regenerates it and fails on any
//! difference.
//!
//! Source artifact:
//! `corpus/zkir/signet-midnight-integration/packages/signet-contract/src/signet-contract`
//! (compiler 0.33.0, language 0.25.0, runtime 0.18.0-rc.1), pinned by
//! `artifact/pin.json` and checked by `tests/artifact_agreement.rs`.
//!
//! DECLARATION ORDER IS THE WIRE CONTRACT. A circuit's parameters and a
//! struct's fields flatten, in order, into the limbs hashed into the
//! communications commitment the ledger matches — so reordering or retyping
//! either changes the commitment and breaks every deployed caller.
//! `artifact/interface-schema.txt` freezes that layout; its diff is the
//! semver decision (notes/interface-crates.org §"Versioning and
//! publishing").
//!
//! EVERY ARGUMENT AND RESULT IS `Public`, because passing a value to
//! another contract discloses it: it enters the commitment in the clear. A
//! private value must `c.disclose(…)` first, and forgetting is a compile
//! error.
//!
//! THE INTERFACE CONTAINS NO ADDRESS. `SignetSigner::at_field(index)` names
//! the sealed ledger cell a deployment keeps the address in, and
//! `SignetSigner::at(address)` takes one as data.

pub mod notification;

use minocrab::Public;
use minocrab_std::v3::{b32_newtype, interface, BytesN, CircuitArg, Uint, Vis3, B32};

b32_newtype! {
    /// Compact `RequestId = Bytes<32>`.
    RequestId,
}

/// Compact `struct SignBidirectionalEventNotification { version: Uint<8>, payload: Bytes<128> }`.
#[derive(Clone, CircuitArg)]
pub struct SignBidirectionalEventNotification<V: Vis3> {
    pub version: Uint<8, V>,
    pub payload: BytesN<V, 128>,
}

/// Compact `struct AffinePoint { x: Bytes<32>, y: Bytes<32> }`.
#[derive(Clone, CircuitArg)]
pub struct AffinePoint<V: Vis3> {
    pub x: B32<V>,
    pub y: B32<V>,
}

/// Compact `struct Signature { bigR: AffinePoint, s: Bytes<32>, recoveryId: Uint<8> }`.
#[derive(Clone, CircuitArg)]
pub struct Signature<V: Vis3> {
    pub big_r: AffinePoint<V>,
    pub s: B32<V>,
    pub recovery_id: Uint<8, V>,
}

/// Compact `struct SignatureRespondedEvent { signature: Signature }`.
#[derive(Clone, CircuitArg)]
pub struct SignatureRespondedEvent<V: Vis3> {
    pub signature: Signature<V>,
}

/// Compact `struct RespondBidirectionalEvent { signature: Signature }`.
#[derive(Clone, CircuitArg)]
pub struct RespondBidirectionalEvent<V: Vis3> {
    pub signature: Signature<V>,
}

/// ```text
/// contract SignetSigner {
///   circuit signBidirectional(requestId: RequestId, notification: SignBidirectionalEventNotification): [];
///   circuit respond(requestId: RequestId, signatureRespondedEvent: SignatureRespondedEvent): [];
///   circuit respondBidirectional(requestId: RequestId, respondBidirectionalEvent: RespondBidirectionalEvent): [];
/// }
/// ```
#[interface]
pub trait SignetSigner {
    /// `circuit signBidirectional(requestId: RequestId, notification: SignBidirectionalEventNotification): []`
    fn sign_bidirectional(
        request_id: RequestId<Public>,
        notification: SignBidirectionalEventNotification<Public>,
    );

    /// `circuit respond(requestId: RequestId, signatureRespondedEvent: SignatureRespondedEvent): []`
    fn respond(
        request_id: RequestId<Public>,
        signature_responded_event: SignatureRespondedEvent<Public>,
    );

    /// `circuit respondBidirectional(requestId: RequestId, respondBidirectionalEvent: RespondBidirectionalEvent): []`
    fn respond_bidirectional(
        request_id: RequestId<Public>,
        respond_bidirectional_event: RespondBidirectionalEvent<Public>,
    );
}
