//! M27 rung 4's GATE: the Lean interpreter, with the intrinsics made
//! CONCRETE, agrees with the Rust reference on real preimages.
//!
//! Two checks, in the order that makes a failure legible:
//!
//! 1. `zkir-run --kat differential/known-answers.txt` — every ported
//!    primitive (Poseidon, SHA-256, Keccak-256, secp256k1) recomputed in
//!    Lean against vectors the Rust reference printed. A primitive that
//!    has drifted says so here, by name, before any circuit is walked.
//! 2. `zkir-run <artifact> <record>` for every run record under
//!    `lean/differential/` — the artifact is compactc's own `.zkir`,
//!    named by the record; the expected block is what
//!    `minocrab_sim::v3::simulate` (cross-checked against upstream
//!    `IrSource::check`) produced. The comparison is the whole block:
//!    accept/reject, the PI stream, `pi_skips`, and the outputs.
//!
//! The records and their known answers are regenerated by
//! `minocrab-contracts/tests/lean_differential.rs` (`--ignored`).
//!
//! Needs `lake` on PATH (the nix devshell provides Lean 4) and a compiled
//! corpus; without either it SKIPS with a loud message, the policy of
//! `lean_roundtrip.rs` and the rest of the corpus-driven gates. CI's
//! `lean` job runs the same executable directly.

use std::path::Path;
use std::process::Command;

/// Everything from the `result` line on — what `zkir-run` must print.
fn expected_block(record: &str) -> String {
    let mut out = String::new();
    let mut seen = false;
    for line in record.lines() {
        if !seen && !line.starts_with("result ") {
            continue;
        }
        seen = true;
        out.push_str(line);
        out.push('\n');
    }
    out
}

#[test]
fn lean_agrees_with_the_rust_oracle_on_every_run_record() {
    let crate_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let lean_dir = crate_dir.join("lean");
    let records_dir = lean_dir.join("differential");
    let repo = crate_dir.join("../..");
    let corpus = repo.join("corpus/zkir");
    if !corpus.join("signet-midnight-examples").exists() {
        eprintln!(
            "skipping: no corpus at {} (run corpus/compile.sh)",
            corpus.display()
        );
        return;
    }
    if Command::new("lake").arg("--version").output().is_err() {
        eprintln!("skipping: `lake` not on PATH (enter the nix devshell for Lean 4)");
        return;
    }

    let build = Command::new("lake")
        .arg("build")
        .current_dir(&lean_dir)
        .output()
        .expect("run lake build");
    assert!(
        build.status.success(),
        "lake build failed in {}:\n{}{}",
        lean_dir.display(),
        String::from_utf8_lossy(&build.stdout),
        String::from_utf8_lossy(&build.stderr),
    );
    let exe = lean_dir.join(".lake/build/bin/zkir-run");

    // ---- 1. the primitives, on their own.
    let kat = records_dir.join("known-answers.txt");
    let run = Command::new(&exe)
        .arg("--kat")
        .arg(&kat)
        .output()
        .expect("run zkir-run --kat");
    let stdout = String::from_utf8_lossy(&run.stdout);
    assert!(
        run.status.success(),
        "the ported intrinsics disagree with the Rust reference:\n{stdout}{}",
        String::from_utf8_lossy(&run.stderr),
    );
    // The count is asserted the way the round-trip gates assert theirs: a
    // truncated or unreadable vector file must not pass as silence.
    let vectors = kat
        .to_str()
        .map(|_| {
            std::fs::read_to_string(&kat)
                .expect("known-answers.txt reads")
                .lines()
                .filter(|l| !l.trim_start().starts_with('#') && !l.trim().is_empty())
                .count()
        })
        .expect("path");
    assert!(vectors > 0, "known-answers.txt carries no vectors");
    assert_eq!(
        stdout.trim(),
        format!("{vectors} of {vectors} known-answer vectors reproduced"),
        "unexpected --kat summary"
    );

    // ---- 2. the run records.
    let mut records: Vec<_> = std::fs::read_dir(&records_dir)
        .expect("differential dir reads")
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|e| e == "record"))
        .collect();
    records.sort();
    assert!(
        !records.is_empty(),
        "no run records under {}",
        records_dir.display()
    );

    let mut accepts = 0usize;
    let mut rejects = 0usize;
    for path in &records {
        let text = std::fs::read_to_string(path).expect("record reads");
        let artifact = text
            .lines()
            .find_map(|l| l.strip_prefix("artifact "))
            .unwrap_or_else(|| panic!("{} has no `artifact` line", path.display()));
        let expected = expected_block(&text);
        if expected.starts_with("result accept") {
            accepts += 1;
        } else {
            rejects += 1;
        }
        let run = Command::new(&exe)
            .arg(repo.join(artifact))
            .arg(path)
            .output()
            .expect("run zkir-run");
        assert!(
            run.status.success(),
            "zkir-run failed on {}:\n{}{}",
            path.display(),
            String::from_utf8_lossy(&run.stdout),
            String::from_utf8_lossy(&run.stderr),
        );
        let got = String::from_utf8_lossy(&run.stdout).to_string();
        if got != expected {
            // Name the first differing line: these blocks run to hundreds
            // of values and a whole-block dump is unreadable.
            let (want_line, got_line) = expected
                .lines()
                .zip(got.lines())
                .enumerate()
                .find(|(_, (a, b))| a != b)
                .map(|(i, (a, b))| (format!("line {}: {a}", i + 1), format!("line {}: {b}", i + 1)))
                .unwrap_or_else(|| {
                    (
                        format!("{} lines", expected.lines().count()),
                        format!("{} lines", got.lines().count()),
                    )
                });
            panic!(
                "Lean and the Rust oracle disagree on {} (artifact {artifact})\n  rust: {want_line}\n  lean: {got_line}",
                path.display()
            );
        }
    }
    println!(
        "lean agrees with the rust oracle on {} run records ({accepts} accepting, {rejects} rejecting) \
         and {vectors} known-answer vectors",
        records.len()
    );
}
